export const themeColours = {
	seoulInsideDay: {
		name: `seoulInsideDay`,
		textPlaceholder: `placeholder:text-amber-500`,
		text: `text-amber-500`,
		textHover: `hover:text-amber-600`,
		textActive: `active:text-amber-700`,
		textAccent: `text-violet-300`,
		textAccentHover: `hover:text-violet-400`,
		textAccentActive: `active:text-violet-500`,
		background: `bg-amber-100 bg-opacity-30`,
		backgroundTranslucent: `bg-amber-100 bg-opacity-75`,
		backgroundOpaque: `bg-amber-100 bg-opacity-100`,
		modalInputBg: `bg-amber-100`,
		modalInputText: `text-amber-800`,
		modalButton: `bg-amber-300 hover:bg-amber-400`,
		progressBackground: `text-amber-200`,
		progress: `text-amber-400`,
		catProgressBackground: `bg-amber-200`,
		catProgress: `bg-amber-400`,
		catProgressText: `text-amber-900`,
		// "button" means text buttons, for icon buttons text styles are used
		toggleOff: `bg-amber-300`,
		toggleButtonOff: `before:bg-amber-100`,
		toggleOn: `checked:bg-amber-400`,
		toggleButtonOn: `checked:before:bg-amber-50`,
		button: `bg-amber-200`,
		buttonHover: `hover:bg-amber-300`,
		buttonActive: `active:bg-amber-400`,
		navIndicator: `bg-amber-200`,
		pageLoadingSpinner: `text-amber-400`,
		border: `border-amber-300`,
		calendarBackground: `bg-stone-500 bg-opacity-30`,
		fillEmpty: `fill-amber-50`,
		fill200: `fill-amber-100`,
		fill300: `fill-amber-200`,
		fill400: `fill-amber-300`,
		fill500: `fill-amber-400`,
		fill600: `fill-amber-500`,
		fill700: `fill-amber-600`,
		fill800: `fill-amber-700`,
		fill900: `fill-amber-900`,
		menu: `bg-amber-300`,
		menuHover: `bg-amber-400`,
		menuActive: `bg-amber-500`,
		menuBefore: `before:bg-amber-300`,
		menuHoverBefore: `before:bg-amber-400`,
		menuActiveBefore: `before:bg-amber-500`,
		menuAfter: `after:bg-amber-300`,
		menuHoverAfter: `after:bg-amber-400`,
		menuActiveAfter: `after:bg-amber-500`,
		ctrlBtn: `text-amber-300 `,
		ctrlBtnHover: `hover:text-amber-400 `,
		ctrlBtnActive: `active:text-amber-500 `,
	},
	seoulInsideNight: {
		name: `seoulInsideNight`,
		text: `text-indigo-200`,
		textHover: `hover:text-indigo-300`,
		textActive: `active:text-indigo-400`,
		textAccent: `text-lime-500`,
		textAccentHover: `hover:text-lime-600`,
		textAccentActive: `active:text-lime-700`,
		background: `bg-indigo-700 bg-opacity-30`,
		backgroundTranslucent: `bg-indigo-700 bg-opacity-75`,
		backgroundOpaque: `bg-indigo-700 bg-opacity-100`,
		modalInputBg: `bg-indigo-100`,
		modalInputText: `text-indigo-900`,
		modalButton: `bg-indigo-800 hover:bg-indigo-900`,
		progressBackground: `text-indigo-900`,
		progress: `text-indigo-400`,
		catProgressBackground: `bg-indigo-900`,
		catProgress: `bg-indigo-400`,
		catProgressText: `text-indigo-900`,
		// "button" means text buttons, for icon buttons text styles are used
		toggleOff: `bg-indigo-900`,
		toggleButtonOff: `before:bg-indigo-200`,
		toggleOn: `checked:bg-indigo-400`,
		toggleButtonOn: `checked:before:bg-indigo-50`,
		button: `bg-indigo-700`,
		buttonHover: `hover:bg-indigo-800`,
		buttonActive: `active:bg-indigo-900`,
		navIndicator: `bg-indigo-500`,
		pageLoadingSpinner: `text-indigo-400`,
		border: `border-indigo-700`,
		calendarBackground: `bg-indigo-900 bg-opacity-75`,
		fillEmpty: `fill-indigo-50`,
		fill200: `fill-indigo-200`,
		fill300: `fill-indigo-300`,
		fill400: `fill-indigo-400`,
		fill500: `fill-indigo-500`,
		fill600: `fill-indigo-600`,
		fill700: `fill-indigo-700`,
		fill800: `fill-indigo-800`,
		fill900: `fill-indigo-900`,
		menu: `bg-indigo-200`,
		menuHover: `bg-indigo-400`,
		menuActive: `bg-indigo-500`,
		menuBefore: `before:bg-indigo-200`,
		menuHoverBefore: `before:bg-indigo-400`,
		menuActiveBefore: `before:bg-indigo-500`,
		menuAfter: `after:bg-indigo-200`,
		menuHoverAfter: `after:bg-indigo-400`,
		menuActiveAfter: `after:bg-indigo-500`,
	},
};
